// Pack apps/bible/ into the finished, downloadable site/apps/bible/bible.gif,
// and regenerate the two GENERATED scripts the page loads:
//
//   js/catalog.js        window.GIFOS_BIBLE_CATALOG = [...all-packs.json]
//                        window.GIFOS_BIBLE_CREDITS = [...credits.json]
//   js/packs-builtin.js  window.GIFOS_BIBLE_BUILTIN = { engwebp, eng-kjv2006 }
//
// TWO TRANSLATIONS RIDE INSIDE THE GIF; the rest are OPTIONAL asset pins. The
// sandbox has no network and no base URL to fetch a file off, so text that
// must work on first boot has to arrive as code — a modern English translation
// and the King James, ~3.3 MB of pack between them. The other 137 are pinned
// by hash in the manifest (optional: true, so nothing downloads at install);
// the OS fetches a pack the first time the reader asks for that translation,
// verifies it, and caches it on the computer. This script REWRITES
// manifest.json's assets array from data/all-packs.json, so a rebuilt pack's
// new hash cannot drift from the manifest that pins it.
//
// Run: node apps/bible/build.mjs
import { bibleIcon, backupIcon, screenshotPng } from './icon.mjs';
import { deflateRawSync } from 'node:zlib';
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

// Node 18 CompressionStream lacks deflate-raw; buffer and deflate at flush.
{
  const Orig = globalThis.CompressionStream;
  globalThis.CompressionStream = class CompressionStream {
    constructor(format) {
      if (format !== 'deflate-raw') {
        if (Orig) return new Orig(format);
        throw new TypeError('unsupported format ' + format);
      }
      const chunks = [];
      const ts = new TransformStream({
        transform(chunk) { chunks.push(Buffer.from(chunk)); },
        flush(controller) {
          controller.enqueue(new Uint8Array(deflateRawSync(Buffer.concat(chunks))));
        }
      });
      this.readable = ts.readable;
      this.writable = ts.writable;
    }
  };
}
await import('../../site/js/gifos-gif.js');

const dir = dirname(fileURLToPath(import.meta.url));
const root = join(dir, '..', '..');
const packsDir = join(root, 'site', 'apps', 'bible', 'packs');
const gif = globalThis.GifOS.gif;
const read = (p) => readFileSync(join(dir, p), 'utf8');

const BUILTIN = ['engwebp', 'eng-kjv2006'];

const allPacks = JSON.parse(read('data/all-packs.json'));
const credits = existsSync(join(dir, 'data', 'credits.json'))
  ? JSON.parse(read('data/credits.json')) : [];

// ---- generated: js/catalog.js -------------------------------------------
{
  const lean = allPacks.map((p) => ({
    id: p.id, name: p.name, title: p.title, language: p.language,
    languageNative: p.languageNative, lang: p.lang, dir: p.dir,
    books: p.books, verses: p.verses, bytes: p.bytes,
    versification: p.versification,
  }));
  const src = '// GENERATED by apps/bible/build.mjs from data/all-packs.json — do not edit.\n' +
    'window.GIFOS_BIBLE_CATALOG = ' + JSON.stringify(lean) + ';\n' +
    'window.GIFOS_BIBLE_CREDITS = ' + JSON.stringify(credits) + ';\n';
  writeFileSync(join(dir, 'js', 'catalog.js'), src);
}

// ---- generated: js/packs-builtin.js -------------------------------------
{
  let src = '// GENERATED by apps/bible/build.mjs — the packs that ride inside the GIF.\n' +
            'window.GIFOS_BIBLE_BUILTIN = {\n';
  for (const id of BUILTIN) {
    const bytes = readFileSync(join(packsDir, id + '.gbp'));
    src += JSON.stringify(id) + ': ' + JSON.stringify(bytes.toString('base64')) + ',\n';
  }
  src += '};\n';
  writeFileSync(join(dir, 'js', 'packs-builtin.js'), src);
}

// ---- manifest: pin every non-built-in pack ------------------------------
const manifest = JSON.parse(read('manifest.json'));
{
  const pins = [];
  for (const p of allPacks) {
    if (BUILTIN.indexOf(p.id) >= 0) continue;
    pins.push({
      url: '/apps/bible/packs/' + p.id + '.gbp',
      sha256: p.sha256, path: 'packs/' + p.id + '.gbp',
      bytes: p.bytes, optional: true,
    });
  }
  // Apparatus packs (lexicons, interlinears, helps) pin the same way, and the
  // list apparatus.js opens is written from this same walk. It used to name
  // them by hand beside this glob, so a pack added here was pinned, downloaded
  // and then never opened.
  const apparatusPacks = [];
  for (const f of readdirSync(packsDir).sort()) {
    if (!f.endsWith('.gbx')) continue;
    const bytes = readFileSync(join(packsDir, f));
    const { createHash } = await import('node:crypto');
    pins.push({
      url: '/apps/bible/packs/' + f, path: 'packs/' + f,
      sha256: createHash('sha256').update(bytes).digest('hex'),
      bytes: bytes.length, optional: true,
    });
    apparatusPacks.push({
      file: f,
      kind: f.startsWith('lex-') ? 'lexicon' : f.startsWith('int-') ? 'interlinear' : 'helps',
      bytes: bytes.length,
    });
  }
  if (!apparatusPacks.length) throw new Error('no apparatus packs in packs/ — the study tools would be empty');
  writeFileSync(join(dir, 'js', 'packs-sealed.js'),
    '// GENERATED by apps/bible/build.mjs from packs/*.gbx — do not edit.\n' +
    '(typeof window !== \'undefined\' ? window : globalThis).GIFOS_BIBLE_SEALED = ' + JSON.stringify(apparatusPacks) + ';\n');
  manifest.assets = pins;
  writeFileSync(join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
}

// ---- the walls ----------------------------------------------------------
const SCRIPTS = ['js/container.js', 'js/pack.js', 'js/render.js', 'js/library.js', 'js/refs.js',
                 'js/versify.js', 'js/store.js', 'js/catalog.js',
                 'js/packs-builtin.js', 'js/packs-sealed.js', 'js/helps.js', 'js/lexicon.js',
                 'js/apparatus.js', 'js/reader.js', 'js/reader2.js',
                 'js/reader3.js', 'js/backup.js', 'js/boot.js'];

const files = {
  'manifest.json': JSON.stringify(manifest),
  'index.html': read('index.html'),
  'style.css': read('style.css'),
};
for (const s of SCRIPTS) files[s] = read(s);
{
  const helpMd = read('help.md');
  if (helpMd.trim().length < 400) throw new Error('help.md is too short — OS Help needs a real guide');
  files['help.md'] = helpMd;
}

const html = files['index.html'];
for (const s of SCRIPTS) {
  if (!html.includes('src="' + s + '"')) throw new Error('index.html does not load ' + s);
}
if (!html.includes('href="style.css"')) throw new Error('index.html does not load style.css');
if (/type=["']module["']/.test(html)) throw new Error('classic scripts only — no type=module');
if (/https?:\/\//i.test(html.replace(/<!--[\s\S]*?-->/g, ''))) {
  throw new Error('index.html has an external URL — nothing is fetched');
}

for (const [n, s] of Object.entries(files)) {
  if (!n.endsWith('.js')) continue;
  if (/<\/script/i.test(s)) throw new Error(n + ' contains </script — cannot inline safely');
  if (/^\s*import\s|^\s*export\s(?!const meta)/m.test(s)) throw new Error(n + ' uses ESM syntax');
  if (n === 'js/packs-builtin.js' || n === 'js/catalog.js') continue;   // generated data
  for (const bad of ['XMLHttpRequest', 'WebSocket', 'navigator.sendBeacon', 'eval(', 'new Function(']) {
    if (s.includes(bad)) throw new Error(n + ' uses ' + bad + ' — nothing leaves this tab.');
  }
  // A fetch of a PACKED file — a quoted relative path, no scheme, no second
  // argument — never leaves the tab: js/backup.js reads backup-host.gif that
  // way, and this build packs it below. Every other shape is still refused,
  // including a computed URL, so packs still arrive through gifos.assets.
  const fetches = s.match(/\bfetch\s*\(/g) || [];
  const packed = s.match(/\bfetch\s*\(\s*['"][^'":/][^'":]*['"]\s*\)/g) || [];
  if (fetches.length !== packed.length) {
    throw new Error(n + ' uses fetch( with a computed or absolute URL — packs arrive through gifos.assets, never a fetch.');
  }
}

if (!manifest.capabilities || manifest.capabilities.db !== true) throw new Error('manifest must declare capabilities.db');
if (!manifest.capabilities.multiplayer) throw new Error('manifest must declare capabilities.multiplayer');
if (manifest.capabilities.network) throw new Error('the Bible reads nothing from the network — do not declare capabilities.network');
if (JSON.stringify(manifest.capabilities.ai) !== '["tts"]') throw new Error('capabilities.ai must be exactly ["tts"]');
if (!manifest.data || (manifest.data.nav || {}).visibility !== 'read-write') throw new Error('nav must be read-write — reading together needs it');
for (const c of ['prefs', 'marks', 'voicenotes', 'plans']) {
  if ((manifest.data[c] || {}).visibility !== 'private') throw new Error(c + ' must be private');
}
if (!manifest.lead || manifest.lead[0].collection !== 'nav') throw new Error('lead must name the nav cursor');
if (manifest.minBuild !== 1381) throw new Error('minBuild must be 1381 — optional assets arrived in that build');
for (const a of manifest.assets) {
  if (!a.optional) throw new Error(a.path + ' must be optional — nothing downloads at install');
  if (!/^[0-9a-f]{64}$/.test(a.sha256)) throw new Error(a.path + ' has no hash');
}

// The built-ins must be real packs the reader can open.
for (const id of BUILTIN) {
  const b = readFileSync(join(packsDir, id + '.gbp'));
  if (b.slice(0, 4).toString() !== 'GBP2') throw new Error(id + ' is not a GBP2 pack');
}

const shot = screenshotPng();
if (shot && shot[0] === 0x89) writeFileSync(join(dir, 'screenshot.png'), shot);

// The backup host: this same animation stamped DATA BACKUP, packed as a file
// so the running app can wrap an export around it (js/backup.js). gif.encode
// always writes a GIFOS1.0 archive block; cutting that block out leaves a
// plain animated GIF the OS will never mistake for an installable app.
{
  const stamped = await gif.encode({}, { preview: backupIcon(), accent: manifest.accent });
  const span = gif.findAppExtSpan(stamped, gif.MARKER);
  files['backup-host.gif'] = span
    ? Buffer.concat([stamped.subarray(0, span.start), stamped.subarray(span.end)])
    : stamped;
}

const bytes = await gif.encode(files, { preview: bibleIcon(), accent: manifest.accent });
const out = join(root, 'site', 'apps', 'bible', 'bible.gif');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, bytes);
console.log('wrote site/apps/bible/bible.gif —', (bytes.length / 1048576).toFixed(1), 'MB from',
            Object.keys(files).length, 'files;', manifest.assets.length, 'optional pins in the manifest');
