/*
 * vendor.mjs — rebuild vendor/* from the pinned basicallydan/skifree.js commit.
 *
 * This is the ONLY step that needs the network, and it is deliberately NOT part
 * of build.mjs: the App GIF must be buildable offline from what is committed
 * here. Run this only to move the pin.
 *
 *   node apps/skifree/vendor.mjs
 *   SKI_SRC=/path/to/checkout node apps/skifree/vendor.mjs
 *
 * WHAT IT PRODUCES. The original sprite sheets as PNGs (a srcdoc iframe has no
 * relative files, so index.html holds hidden <img> tags the runtime rewrites
 * to data URLs), the MIT notice, and the engine as ONE classic IIFE. Upstream
 * is ESM + esbuild; GifOS drops type=module, so import/export cannot ship.
 * Hammer.js and Mousetrap stay out — touch.js / boot.js own input.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, copyFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = dirname(fileURLToPath(import.meta.url));
const vendor = join(dir, 'vendor');

const UPSTREAM = 'https://github.com/basicallydan/skifree.js.git';
const PIN = 'a812f944f7420ab53374b6b983ef3eb54f8a26ce'; // 2026-02-23 ouch animation

const SPRITES = ['sprite-characters.png', 'skifree-objects.png'];

// Engine files, in evaluation order. input.js / main.js / isMobileDevice.js /
// skiLift.js are not shipped: we own boot, touch, and the unused lift.
const ENGINE = [
  { file: 'js/lib/constants.js', banner: 'constants' },
  { file: 'js/lib/guid.js', banner: 'guid' },
  { file: 'js/lib/sprite.js', banner: 'sprite', replace: [['GUID()', 'guid()']] },
  { file: 'js/lib/spriteArray.js', banner: 'spriteArray' },
  { file: 'js/lib/camera.js', banner: 'camera' },
  { file: 'js/lib/skier.js', banner: 'skier' },
  { file: 'js/lib/monster.js', banner: 'monster' },
  { file: 'js/lib/snowboarder.js', banner: 'snowboarder' },
  { file: 'js/lib/infoBox.js', banner: 'infoBox' },
  { file: 'js/lib/game.js', banner: 'game' },
  { file: 'js/spriteInfo.js', banner: 'spriteInfo' },
];

const run = (cmd, args, cwd) => execFileSync(cmd, args, { cwd, stdio: 'inherit', timeout: 120000 });

let src = process.env.SKI_SRC;
let tmp = null;
if (!src) {
  tmp = mkdtempSync(join(tmpdir(), 'skifree-'));
  src = join(tmp, 'skifree.js');
  console.log('cloning ' + UPSTREAM + ' @ ' + PIN.slice(0, 10) + '…');
  run('git', ['clone', '--quiet', UPSTREAM, src]);
  run('git', ['checkout', '--quiet', PIN], src);
}
const at = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: src, encoding: 'utf8' }).trim();
if (at !== PIN) throw new Error('checkout is at ' + at + ', not the pin ' + PIN + ' — move PIN deliberately.');

mkdirSync(vendor, { recursive: true });

for (const name of SPRITES) {
  const from = join(src, name);
  if (!existsSync(from)) throw new Error('missing sprite ' + name);
  copyFileSync(from, join(vendor, name));
}

function stripImports(s) {
  // import X from 'y';
  // import { a, b } from 'y';
  // import {\n  a,\n  b,\n} from 'y';
  return s.replace(/^[ \t]*import\s+[\s\S]*?\s+from\s+['"][^'"]+['"];[ \t]*\n/gm, '');
}

function toClassic(raw, spec) {
  let s = String(raw).replace(/\r\n/g, '\n');
  s = stripImports(s);
  if (spec.replace) {
    for (const [a, b] of spec.replace) {
      if (!s.includes(a)) throw new Error(spec.file + ' PATCH NO LONGER APPLIES: missing ' + JSON.stringify(a));
      s = s.split(a).join(b);
    }
  }
  s = s.replace(/^export default (\w+);\s*$/gm, 'Ski.$1 = $1;');
  s = s.replace(/^export const /gm, 'var ');
  if (/^import\s|export\s+default|export\s+const |export\s+\{/m.test(s)) {
    throw new Error(spec.file + ' still has ESM after conversion');
  }
  return s.trim() + '\n';
}

const parts = [];
for (const spec of ENGINE) {
  const abs = join(src, spec.file);
  if (!existsSync(abs)) throw new Error('upstream is missing ' + spec.file);
  const converted = toClassic(readFileSync(abs, 'utf8'), spec);
  parts.push('/* --- ' + spec.banner + ' --- */\n' + converted);
}

const engine = [
  '/* generated by vendor.mjs — classic IIFE of basicallydan/skifree.js engine.',
  '   Do not edit; run node apps/skifree/vendor.mjs to rebuild. */',
  '(function (root) {',
  "'use strict';",
  'var Ski = root.Ski || (root.Ski = {});',
  '',
  parts.join('\n'),
  'root.Ski = Ski;',
  '})(typeof window !== "undefined" ? window : globalThis);',
  '',
].join('\n');

if (/<\/script/i.test(engine)) throw new Error('engine.js contains </script — cannot inline safely');
if (!engine.includes('Ski.Skier = Skier')) throw new Error('engine.js does not attach Ski.Skier');
if (!engine.includes('Ski.Game = Game')) throw new Error('engine.js does not attach Ski.Game');
if (!engine.includes('Ski.sprites = sprites')) throw new Error('engine.js does not attach Ski.sprites');
if (engine.includes('localStorage')) throw new Error('engine.js still talks to localStorage — that lived in main.js');
if (engine.includes('Hammer') || engine.includes('Mousetrap')) {
  throw new Error('engine.js bundled input libs — those stay out');
}

writeFileSync(join(vendor, 'engine.js'), engine);

const license = readFileSync(join(src, 'license.md'), 'utf8');
writeFileSync(join(vendor, 'COPYING.txt'), license);
writeFileSync(join(dir, 'COPYING.txt'), license);

const sha = (p) => createHash('sha256').update(readFileSync(join(vendor, p))).digest('hex');
const pins = {
  'engine.js': sha('engine.js'),
  'sprite-characters.png': sha('sprite-characters.png'),
  'skifree-objects.png': sha('skifree-objects.png'),
  'COPYING.txt': sha('COPYING.txt'),
};

writeFileSync(join(vendor, 'UPSTREAM.txt'),
`vendor/* is GENERATED. Do not edit it; run node apps/skifree/vendor.mjs.

upstream: ${UPSTREAM}
commit:   ${PIN}
date:     2026-02-23
license:  MIT (COPYING.txt)

Classic IIFE of js/lib/*.js + js/spriteInfo.js (ESM import/export stripped,
GUID() → guid()). Sprites copied as PNGs; index.html holds hidden <img> so
the GifOS runtime can rewrite src to a data URL inside a srcdoc iframe.

NOT copied:
  js/main.js              — localStorage high score, auto-boot, UA sniffing
  js/lib/input.js         — Hammer.js + Mousetrap; touch.js / boot.js own input
  js/lib/isMobileDevice.js
  js/lib/skiLift.js       — unused by upstream's own main.js
  dist/skifree.js         — esbuild bundle of the above plus hammer/mousetrap
  yeti-big.png            — unused
  apple-touch-icon*.png
  skifree-*-banner.png
  *.psd

sha256:
${Object.entries(pins).map(([k, v]) => '  ' + k + '  ' + v).join('\n')}

The MIT notice travels INSIDE the GIF as COPYING.txt as well as here.
Sprites are from Wing Wang Wao / Spriters Resource, as credited upstream.
Original SkiFree is Chris Pirih, 1991.
`);

if (tmp) rmSync(tmp, { recursive: true, force: true });

console.log('wrote apps/skifree/vendor/ from skifree.js@' + PIN.slice(0, 10));
console.log('  engine.js              ', pins['engine.js']);
console.log('  sprite-characters.png  ', (readFileSync(join(vendor, 'sprite-characters.png')).length / 1024).toFixed(0), 'KB');
console.log('  skifree-objects.png    ', (readFileSync(join(vendor, 'skifree-objects.png')).length / 1024).toFixed(0), 'KB');

