/*
 * vendor.mjs — rebuild vendor/* from the pinned iamkun/tower_game commit.
 *
 * This is the ONLY step that needs the network, and it is deliberately NOT part
 * of build.mjs: the App GIF must be buildable offline from what is committed
 * here. Run this only to move the pin.
 *
 *   node apps/tower-game/vendor.mjs
 *   TOWER_SRC=/path/to/checkout node apps/tower-game/vendor.mjs
 *
 * WHAT IT PRODUCES. The webpack classic bundle (window.TowerGame, already an
 * IIFE — GifOS drops type=module) with asset paths rewritten to TOWER_ASSETS
 * data URLs, plus those data URLs, plus the MIT notice. The loading GIF, WeChat
 * share art, ogg duplicates and extra font formats stay out: a srcdoc iframe
 * has no relative files, so everything the engine or the chrome actually loads
 * rides in as a data URL.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, copyFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = dirname(fileURLToPath(import.meta.url));
const vendor = join(dir, 'vendor');

const UPSTREAM = 'https://github.com/iamkun/tower_game.git';
const PIN = 'c6fa84afe179b661fa71cf7cc8788d0c47ca2875'; // 2025-08-29 README grammar

const PNG = [
  'background.png', 'hook.png', 'block-rope.png', 'block.png', 'block-perfect.png',
  'tutorial.png', 'tutorial-arrow.png', 'heart.png', 'score.png',
  'c1.png', 'c2.png', 'c3.png', 'c4.png', 'c5.png', 'c6.png', 'c7.png', 'c8.png',
  'f1.png', 'f2.png', 'f3.png', 'f4.png', 'f5.png', 'f6.png', 'f7.png',
  'main-bg.png', 'main-index-title.png', 'main-index-start.png',
  'main-modal-bg.png', 'main-modal-over.png', 'main-modal-again-b.png',
];
const MP3 = ['drop.mp3', 'drop-perfect.mp3', 'game-over.mp3', 'rotate.mp3', 'bgm.mp3'];
const FONT = ['wenxue.woff'];

const MIME = {
  png: 'image/png', mp3: 'audio/mpeg', woff: 'font/woff',
};

const run = (cmd, args, cwd) => execFileSync(cmd, args, { cwd, stdio: 'inherit', timeout: 120000 });

let src = process.env.TOWER_SRC;
let tmp = null;
if (!src) {
  tmp = mkdtempSync(join(tmpdir(), 'towergame-'));
  src = join(tmp, 'tower_game');
  console.log('cloning ' + UPSTREAM + ' @ ' + PIN.slice(0, 10) + '…');
  run('git', ['clone', '--quiet', UPSTREAM, src]);
  run('git', ['checkout', '--quiet', PIN], src);
}
const at = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: src, encoding: 'utf8' }).trim();
if (at !== PIN) throw new Error('checkout is at ' + at + ', not the pin ' + PIN + ' — move PIN deliberately.');

mkdirSync(vendor, { recursive: true });

function dataUrlFor(abs, ext) {
  const mime = MIME[ext] || 'application/octet-stream';
  return 'data:' + mime + ';base64,' + readFileSync(abs).toString('base64');
}

const assets = {};
for (const name of PNG) {
  const abs = join(src, 'assets', name);
  if (!existsSync(abs)) throw new Error('missing asset ' + name);
  assets[name] = dataUrlFor(abs, 'png');
}
for (const name of MP3) {
  const abs = join(src, 'assets', name);
  if (!existsSync(abs)) throw new Error('missing sound ' + name);
  assets[name] = dataUrlFor(abs, 'mp3');
}
for (const name of FONT) {
  const abs = join(src, 'assets', name);
  if (!existsSync(abs)) throw new Error('missing font ' + name);
  assets[name] = dataUrlFor(abs, 'woff');
}

let main = readFileSync(join(src, 'dist', 'main.js'), 'utf8');
const PATH = 'n=function(t){return"./assets/".concat(t)}';
if (!main.includes(PATH)) {
  throw new Error('PATCH NO LONGER APPLIES: dist/main.js pathGenerator — the bundle no longer builds "./assets/"+name');
}
main = main.split(PATH).join(
  'n=function(t){var a=window.TOWER_ASSETS||{};return a[t]||("./assets/"+t)}',
);
if (main.includes('"./assets/".concat')) {
  throw new Error('dist/main.js still concatenates ./assets/ after the path patch');
}
if (/<\/script/i.test(main)) throw new Error('dist/main.js contains </script — cannot inline safely');
if (!main.includes('window.TowerGame')) throw new Error('dist/main.js does not attach window.TowerGame');
writeFileSync(join(vendor, 'main.js'), main);

const assetLines = Object.keys(assets).sort().map((k) =>
  '  ' + JSON.stringify(k) + ': ' + JSON.stringify(assets[k]));
writeFileSync(join(vendor, 'assets.js'),
  '/* generated by vendor.mjs — data URLs for png/mp3/woff inside the GIF */\n' +
  'var TOWER_ASSETS = {\n' + assetLines.join(',\n') + '\n};\n');

copyFileSync(join(src, 'LICENSE'), join(vendor, 'COPYING.txt'));
copyFileSync(join(src, 'LICENSE'), join(dir, 'COPYING.txt'));

const sha = (p) => createHash('sha256').update(readFileSync(join(vendor, p))).digest('hex');
const pins = {
  'main.js': sha('main.js'),
  'COPYING.txt': sha('COPYING.txt'),
};

writeFileSync(join(vendor, 'UPSTREAM.txt'),
`vendor/* is GENERATED. Do not edit it; run node apps/tower-game/vendor.mjs.

upstream: ${UPSTREAM}
commit:   ${PIN}
date:     2025-08-29
license:  MIT (COPYING.txt)

Classic script copied from dist/main.js (webpack IIFE of src/ + cooljs) with
one patch: pathGenerator('./assets/'+name) reads window.TOWER_ASSETS[name]
so Image/Audio srcs are data URLs inside a srcdoc iframe.

NOT copied:
  assets/main-loading.gif          — CSS bar instead; the GIF is 279 KB of splash
  assets/*.ogg                     — cooljs loads the mp3s; ogg is a second copy
  assets/wenxue.{eot,ttf,svg}      — woff is enough
  assets/main-modal-invite-b.png   — Invite is OS chrome, not a WeChat overlay
  assets/main-share-icon.png
  assets/main-index-logo.png
  assets/favicon.png
  assets/zepto-1.1.6.min.js        — chrome is vanilla

sha256:
${Object.entries(pins).map(([k, v]) => '  ' + k + '  ' + v).join('\n')}

The MIT notice travels INSIDE the GIF as COPYING.txt as well as here.
cooljs (iamkun/cooljs) is bundled inside dist/main.js by upstream.
`);

if (tmp) rmSync(tmp, { recursive: true, force: true });

console.log('wrote apps/tower-game/vendor/ from tower_game@' + PIN.slice(0, 10));
console.log('  main.js    ', pins['main.js']);
console.log('  assets.js  ', (readFileSync(join(vendor, 'assets.js')).length / 1024).toFixed(0), 'KB');
