#!/usr/bin/env python3
"""Regenerate apps/retirement/data/mortality.js from the SSA period life table.

Run by hand when the table is refreshed, never by the build — same doctrine as
tools/fetch-market-data.py. The build is offline and reads only committed files.

    python3 apps/retirement/tools/fetch-life-table.py             # download
    python3 apps/retirement/tools/fetch-life-table.py table.html  # local copy

Source: Social Security Administration, Actuarial Life Table (Period Life Table),
https://www.ssa.gov/oact/STATS/table4c6.html — the 2023 table, as used in the
2026 Trustees Report. Columns are age, then male death probability / number of
lives / life expectancy, then the same three for females.

Only l(x), the number of a 100,000 cohort still alive at exact age x, is kept:
every question the app asks is a CONDITIONAL survival probability, and those are
just ratios of l(x).

    P(alive at T | alive at x) = l(T) / l(x)

A note on what this table IS, because it changes how the answer should be read.
It is a PERIOD table: it applies the death rates observed in one year at every
future age, with no allowance for medicine improving. So it slightly understates
how long people will actually live. It is also POPULATION mortality, and the
people who go looking for a retirement calculator are, on average, wealthier and
longer-lived than the population — insurers price annuitants at roughly half to
three-quarters of these rates at retirement ages. Both biases point the same way:
this table is, if anything, optimistic about dying and therefore pessimistic
about how long the money has to last.
"""
import html
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'data', 'mortality.js')
URL = 'https://www.ssa.gov/oact/STATS/table4c6.html'
# ssa.gov refuses automated fetches; the Internet Archive serves the same page.
MIRROR = 'https://web.archive.org/web/2026/https://www.ssa.gov/oact/STATS/table4c6.html'

FROM_AGE = 30   # nobody plans a retirement from younger than this


def fetch():
    for url in (URL, MIRROR):
        try:
            req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
            with urllib.request.urlopen(req, timeout=90) as r:
                body = r.read().decode('utf-8', 'replace')
            if 'Access Denied' in body[:400]:
                continue
            if body.count('<tr') > 50:
                print('fetched', url)
                return body
        except Exception as e:                                  # noqa: BLE001
            print('  ', url, 'failed:', e)
    raise SystemExit('could not fetch the life table from either source')


def parse(body):
    rows = re.findall(r'<tr[^>]*>(.*?)</tr>', body, re.S | re.I)
    out = {}
    for r in rows:
        cells = [html.unescape(re.sub(r'<[^>]+>', '', c)).strip().replace(',', '')
                 for c in re.findall(r'<t[dh][^>]*>(.*?)</t[dh]>', r, re.S | re.I)]
        cells = [c for c in cells if c != '']
        if len(cells) < 7:
            continue
        try:
            age = int(cells[0])
            vals = [float(x) for x in cells[1:7]]
        except ValueError:
            continue
        out[age] = vals          # qxM, lxM, exM, qxF, lxF, exF
    return out


def main():
    body = open(sys.argv[1], encoding='utf-8', errors='replace').read() if len(sys.argv) > 1 else fetch()
    t = parse(body)
    if len(t) < 110:
        raise SystemExit('only parsed %d ages — the table layout moved' % len(t))
    for age in range(0, 120):
        if age not in t:
            raise SystemExit('age %d missing — the table has a hole' % age)

    # Sanity: these are the published values and they must come back exactly.
    for age, want in ((60, (0.011337, 84544, 21.79)), (65, (0.016455, 79084, 18.12))):
        got = t[age][:3]
        if abs(got[0] - want[0]) > 1e-9 or int(got[1]) != want[1] or abs(got[2] - want[2]) > 0.01:
            raise SystemExit('age %d male row is %r, expected %r — wrong table' % (age, got, want))

    ages = list(range(FROM_AGE, 120))
    m = [int(round(t[a][1])) for a in ages]
    f = [int(round(t[a][4])) for a in ages]
    for series, who in ((m, 'male'), (f, 'female')):
        for a, b in zip(series, series[1:]):
            if b > a:
                raise SystemExit('%s survivors increase with age — parse is wrong' % who)

    js = (
        '/* GENERATED by tools/fetch-life-table.py — do not edit by hand.\n'
        ' *\n'
        ' * SSA period life table (2023, as used in the 2026 Trustees Report).\n'
        ' * l(x) = how many of a 100,000 cohort are still alive at exact age x,\n'
        ' * from age %d to %d. Conditional survival is just a ratio:\n'
        ' *\n'
        ' *     P(alive at T | alive at x) = l(T) / l(x)\n'
        ' *\n'
        ' * A PERIOD table applies one year\'s death rates at every future age, so\n'
        ' * it makes no allowance for medicine improving, and it is POPULATION\n'
        ' * mortality — insurers price annuitants at roughly half to three quarters\n'
        ' * of these rates at retirement ages. Both biases run the same way: this\n'
        ' * is optimistic about dying, so pessimistic about how long money must last.\n'
        ' * Source: https://www.ssa.gov/oact/STATS/table4c6.html\n'
        ' */\n'
        'var MORTALITY = { from: %d, radix: 100000, m: [%s], f: [%s] };\n'
        'if (typeof module !== \'undefined\') module.exports = MORTALITY;\n'
    ) % (FROM_AGE, ages[-1], FROM_AGE, ','.join(map(str, m)), ','.join(map(str, f)))

    with open(OUT, 'w') as fh:
        fh.write(js)
    print('wrote %s — ages %d..%d, %.1f KB' % (os.path.relpath(OUT), ages[0], ages[-1], len(js) / 1024))
    print('  a 65-year-old man reaching 90: %.1f%%' % (m[90 - FROM_AGE] / m[65 - FROM_AGE] * 100))
    print('  a 65-year-old woman reaching 90: %.1f%%' % (f[90 - FROM_AGE] / f[65 - FROM_AGE] * 100))


if __name__ == '__main__':
    main()
