#!/usr/bin/env python3
"""Regenerate apps/retirement/data/market.js from Robert Shiller's ie_data.xls.

The app BACKTESTS against real history, so the history has to be the real thing
and it has to be COMMITTED — the build script is offline and deterministic, and
the finished GIF carries every byte it needs. This tool is the only place that
touches the network, and it is run by hand when the data is refreshed, never by
the build.

    python3 apps/retirement/tools/fetch-market-data.py            # download + write
    python3 apps/retirement/tools/fetch-market-data.py ie_data.xls  # from a local copy

Source: Robert J. Shiller, "Stock Market Data Used in Irrational Exuberance",
http://www.econ.yale.edu/~shiller/data.htm (the current file is served from
https://shillerdata.com/). Monthly since 1871-01.

Columns taken from the "Data" sheet:

    0   Date              1871.01 = January 1871 (note 1871.10 IS October)
    4   CPI               consumer price index, used for the inflation basis
    6   Long Interest Rate GS10
    9   Real Total Return Price      stock TOTAL return, inflation-adjusted
    12  CAPE                         cyclically adjusted P/E (NA before 1881)
    18  Real Total Bond Returns      10y bond TOTAL return, inflation-adjusted

Columns 9 and 18 are the whole point: they are already TOTAL return (dividends
and coupons reinvested) and already REAL (inflation removed). A backtest that
uses price-only returns overstates nothing and understates everything — it
silently deletes about two thirds of a stock portfolio's long-run growth.

The two series are re-based to 1.0 at the first row and emitted at 8 significant
digits, which round-trips every monthly ratio we care about to well under a
basis point.
"""
import json
import os
import struct
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'data', 'market.js')
URL = ('https://img1.wsimg.com/blobby/go/e5e77e0b-59d1-44d9-ab25-4763ac982e53/'
       'downloads/e27e58c1-8ae0-488c-a976-a298708c7175/ie_data.xls')

sys.path.insert(0, HERE)
from biff import cells  # noqa: E402  (a tiny BIFF8 reader; .xls has no CSV twin)


def load(path):
    grid, sheets = cells(path, 4)
    if sheets[4] != 'Data':
        raise SystemExit('sheet 4 is %r, expected Data — the workbook moved' % sheets[4])
    rows = {}
    for (r, c), v in grid.items():
        rows.setdefault(r, {})[c] = v
    return rows


def main():
    if len(sys.argv) > 1:
        path = sys.argv[1]
    else:
        path = os.path.join('/tmp', 'ie_data.xls')
        print('downloading', URL)
        urllib.request.urlretrieve(URL, path)
    rows = load(path)

    recs = []
    for r in sorted(rows):
        d = rows[r]
        date, stock, bond, cpi = d.get(0), d.get(9), d.get(18), d.get(4)
        if not isinstance(date, float):
            continue
        if not all(isinstance(x, float) for x in (stock, bond, cpi)):
            continue
        year = int(date)
        # 1871.01 -> 1, 1871.1 -> 10.  Excel stores .10 as .1, so read the
        # printed hundredths, not round(frac*100), or every October becomes
        # January.
        month = int(round((date - year) * 100))
        if month == 1 and abs((date - year) * 100 - 10) < 1e-6:
            month = 10
        if not 1 <= month <= 12:
            raise SystemExit('bad month in %r' % date)
        cape = d.get(12)
        recs.append({
            'y': year, 'm': month, 'stock': stock, 'bond': bond, 'cpi': cpi,
            'cape': cape if isinstance(cape, float) else None,
            'gs10': d.get(6) if isinstance(d.get(6), float) else None,
        })

    if not recs:
        raise SystemExit('no rows parsed')
    # Contiguity: a hole would silently shorten every cycle that crosses it.
    for a, b in zip(recs, recs[1:]):
        nxt = (a['y'] + 1, 1) if a['m'] == 12 else (a['y'], a['m'] + 1)
        if (b['y'], b['m']) != nxt:
            raise SystemExit('gap after %d-%02d' % (a['y'], a['m']))

    s0, b0 = recs[0]['stock'], recs[0]['bond']
    sig = lambda x: float('%.8g' % x)  # noqa: E731

    out = {
        'source': 'Robert J. Shiller, Irrational Exuberance data, econ.yale.edu/~shiller/data.htm',
        'start': [recs[0]['y'], recs[0]['m']],
        'end': [recs[-1]['y'], recs[-1]['m']],
        'months': len(recs),
        # Real TOTAL return indices, re-based to 1.00 at start.
        'stock': [sig(r['stock'] / s0) for r in recs],
        'bond': [sig(r['bond'] / b0) for r in recs],
        # CPI stays in its own units — only ratios of it are ever used.
        'cpi': [sig(r['cpi']) for r in recs],
        'cape': [None if r['cape'] is None else sig(r['cape']) for r in recs],
    }

    body = json.dumps(out, separators=(',', ':'))
    js = (
        '/* GENERATED by tools/fetch-market-data.py — do not edit by hand.\n'
        ' *\n'
        ' * Robert J. Shiller\'s monthly series, %d-%02d to %d-%02d (%d months).\n'
        ' * stock[] and bond[] are REAL TOTAL RETURN indices re-based to 1.00 at\n'
        ' * the first month; cpi[] is the CPI in its own units; cape[] is the\n'
        ' * cyclically adjusted P/E (null before it has ten years behind it).\n'
        ' * Source: http://www.econ.yale.edu/~shiller/data.htm\n'
        ' */\n'
        'var MARKET = %s;\n'
        'if (typeof module !== \'undefined\') module.exports = MARKET;\n'
    ) % (out['start'][0], out['start'][1], out['end'][0], out['end'][1], out['months'], body)

    with open(OUT, 'w') as f:
        f.write(js)
    print('wrote %s — %d months, %d-%02d..%d-%02d, %.0f KB' % (
        os.path.relpath(OUT), out['months'], out['start'][0], out['start'][1],
        out['end'][0], out['end'][1], len(js) / 1024))


if __name__ == '__main__':
    main()
