#!/usr/bin/env python3
"""
check-torch.py — hold the numpy reference to torch, which is what UVR runs.

test/unit/vocal-remover.js pins the JavaScript port to a fixture generated by
mdx_ref.py. That chain is only as good as its first link: if mdx_ref's STFT
drifted from torch.stft/torch.istft, the JS would match the reference perfectly
and both would be wrong together. This is the link check.

It is NOT part of the release gate, deliberately: torch is a ~900 MB dependency
and the gate box does not carry it. Run it whenever mdx_ref.py is touched, and
re-run gen-fixture.py after.

    pip install torch numpy
    python3 apps/vocal-remover/tools/check-torch.py
"""
import os
import sys
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mdx_ref import stft, istft, hann_periodic  # noqa: E402

try:
    import torch
except ImportError:
    print('torch is not installed — pip install torch. (This tool is not in the gate.)')
    raise SystemExit(2)

# hop 1024 with the three n_fft values UVR's MDX models are trained at, plus the
# self-test model's 4096, plus one small size the unit fixture uses.
CASES = [(6144, 1024), (7680, 1024), (5120, 1024), (4096, 1024), (192, 32)]

rng = np.random.default_rng(7)
bad = 0
for n_fft, hop in CASES:
    T = hop * 255 if hop > 64 else hop * 31
    x = (rng.standard_normal((2, T)) * 0.3).astype(np.float32)

    # torch.hann_window builds the window IN float32, so it lands a couple of
    # float32 ulp (~1.2e-7 near 1.0) away from the same formula evaluated in
    # float64 and rounded once. That gap is arithmetic, not disagreement; the
    # threshold below is set just above it and nowhere near a real drift, which
    # would be a shape change or a periodic/symmetric mix-up worth ~1/n_fft.
    w = torch.hann_window(n_fft, periodic=True)
    dw = float(np.abs(w.numpy() - hann_periodic(n_fft).astype(np.float32)).max())

    X_t = torch.stft(torch.tensor(x), n_fft=n_fft, hop_length=hop, window=w,
                     center=True, return_complex=True)
    X_n = stft(x, n_fft, hop)
    d_fwd = float(np.abs(X_t.numpy() - X_n).max())

    y_t = torch.istft(X_t, n_fft=n_fft, hop_length=hop, window=w, center=True)
    y_n = istft(X_n, n_fft, hop)
    d_inv = float(np.abs(y_t.numpy() - y_n).max())

    shape_ok = X_t.shape == X_n.shape and y_t.shape == y_n.shape
    ok = shape_ok and dw < 1e-6 and d_fwd < 1e-4 and d_inv < 1e-5
    bad += 0 if ok else 1
    print(('PASS' if ok else 'FAIL'),
          f'n_fft={n_fft:<5} hop={hop:<5} window {dw:.1e}  stft {d_fwd:.1e}  istft {d_inv:.1e}'
          + ('' if shape_ok else f'  SHAPES {tuple(X_t.shape)} vs {tuple(X_n.shape)}'))

print()
print('the reference is torch-faithful' if not bad else f'{bad} MISMATCH(ES) — mdx_ref.py has drifted from torch')
raise SystemExit(1 if bad else 0)
