#!/usr/bin/env python3
"""
gen-fixture.py — write the fixture test/unit/vocal-remover.js holds the port to.

The MDX chunker is the part of the port that fails QUIETLY: a wrong pad, an
off-by-one step, the symmetric window swapped for the periodic one, and the
audio still sounds like audio. So the reference here is transcribed straight
from ultimatevocalremovergui/separate.py (SeperateMDX.demix) and
lib_v5/tfc_tdf_v3.py (STFT) — and the STFT half of it is checked against
torch's own stft/istft by tools/check-torch.py, which is where the transcription
could otherwise drift without anybody noticing.

The model is stood in for by a deterministic, frequency-dependent gain, so the
fixture exercises the whole chunk -> tensor -> chunk path without needing 66 MB
of weights (and without ONNX in the unit tier at all).

    python3 apps/vocal-remover/tools/gen-fixture.py
"""
import base64, json, os, sys
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from mdx_ref import MDX  # noqa: E402

OUT = os.path.join(HERE, '..', 'vocal-remover-mdx.json')


def xorshift(seed, n):
    """The same 32-bit xorshift the JS side runs, so the fixture stores only
    the OUTPUT: an input array of 40000 samples does not belong in a repo."""
    x = seed & 0xFFFFFFFF
    out = np.empty(n)
    for i in range(n):
        x ^= (x << 13) & 0xFFFFFFFF
        x ^= x >> 17
        x ^= (x << 5) & 0xFFFFFFFF
        out[i] = (x / 4294967296.0) * 2.0 - 1.0
    return out


def stand_in_model(dim_f):
    """out[p, f, t] = in[p, f, t] * (0.3 + 0.7 * f / dim_f) — cheap, exactly
    reproducible in JS, and NOT symmetric, so a transposed plane or a swapped
    real/imag shows up instead of cancelling."""
    gain = (0.3 + 0.7 * np.arange(dim_f) / dim_f).reshape(1, 1, dim_f, 1)
    return lambda t: (t * gain).astype(np.float32)


CASES = [
    # a radix-3 n_fft, several chunks, the ordinary (model) path
    dict(name='radix3-small', n_fft=192, hop=32, dim_t=32, dim_f=64, compensate=1.03, T=2500, seed=12345),
    # a radix-5 n_fft, and a T that divides gen_size exactly (the pad branch)
    dict(name='radix5-exact', n_fft=320, hop=64, dim_t=16, dim_f=100, compensate=1.0, T=1280, seed=777),
    # radix-15, and a T short enough that the final chunk is zero-padded and
    # np.hanning() is cut short — the branch that leaves a hole in `divider`
    dict(name='radix15-short', n_fft=480, hop=64, dim_t=16, dim_f=120, compensate=1.021, T=700, seed=999),
    # the REAL n_fft/hop of UVR-MDX-NET-Inst_HQ_3 (6144/1024), shortened only in
    # dim_t so the fixture is small: same 6x window overlap, same radix-3 FFT
    dict(name='inst-hq3-nfft', n_fft=6144, hop=1024, dim_t=16, dim_f=1536, compensate=1.022, T=40000, seed=424242),
    # the is_match_mix path: no model, overlap 0.02, compensate not applied
    dict(name='matchmix', n_fft=192, hop=32, dim_t=32, dim_f=64, compensate=1.03, T=2500, seed=12345, match=True),
]


def n_chunks(m, T, match):
    chunk_size = m.hop * (256 - 1) if match else m.chunk_size
    gen_size = chunk_size - 2 * m.trim
    length = m.trim + T + (gen_size + m.trim - (T % gen_size))
    step = int(0.98 * chunk_size) if match else m.chunk_size - m.n_fft
    return int(np.ceil(length / step))


def b64f32(a):
    return base64.b64encode(np.asarray(a, dtype='<f4').tobytes()).decode()


def main():
    cases = []
    for c in CASES:
        raw = xorshift(c['seed'], c['T'] * 2)
        mix = np.stack([raw[0::2], raw[1::2]])
        m = MDX(c['n_fft'], c['dim_f'], c['dim_t'], c['compensate'],
                stand_in_model(c['dim_f']), hop=c['hop'])
        with np.errstate(invalid='ignore', divide='ignore'):
            src = m.demix(mix, is_match_mix=c.get('match', False))
        assert src.shape == mix.shape, (src.shape, mix.shape)
        assert np.isfinite(src).all(), 'the reference produced a non-finite sample'
        stride = max(1, c['T'] // 400)
        cases.append(dict(
            name=c['name'], nFft=c['n_fft'], hop=c['hop'], dimT=c['dim_t'], dimF=c['dim_f'],
            compensate=c['compensate'], T=c['T'], seed=c['seed'], matchMix=c.get('match', False),
            chunks=n_chunks(m, c['T'], c.get('match', False)),
            stride=stride,
            rms=[float(np.sqrt((src[0] ** 2).mean())), float(np.sqrt((src[1] ** 2).mean()))],
            peak=[float(np.abs(src[0]).max()), float(np.abs(src[1]).max())],
            sampledL=b64f32(src[0][::stride]),
            sampledR=b64f32(src[1][::stride]),
        ))
    doc = {
        '_': 'GENERATED by apps/vocal-remover/tools/gen-fixture.py — do not hand-edit.',
        'source': 'ultimatevocalremovergui separate.py SeperateMDX.demix, via mdx_ref.py',
        'cases': cases,
    }
    with open(OUT, 'w') as f:
        json.dump(doc, f, indent=1)
        f.write('\n')
    print('wrote', os.path.relpath(OUT), '-', len(cases), 'cases,',
          round(os.path.getsize(OUT) / 1024), 'KB')


if __name__ == '__main__':
    main()
