// THE VOCAL REMOVER PORT IS HELD AGAINST ULTIMATE VOCAL REMOVER, MECHANICALLY.
//
// apps/vocal-remover is a transcription of UVR's MDX-Net separation path
// (separate.py SeperateMDX.demix / run_model, lib_v5/tfc_tdf_v3.py STFT), and
// that kind of port does not fail loudly. Every way it can go wrong — a reflect
// pad that repeats the edge, the symmetric overlap window swapped for the
// periodic analysis one, a step that is chunk_size - n_fft in one place and
// chunk_size in another, the real/imag planes transposed — produces audio that
// still sounds like audio, just worse. Nobody A/Bs a four-minute stem.
//
// So the arithmetic is pinned to a fixture generated by a numpy reference that
// was itself transcribed from UVR line by line (apps/vocal-remover/tools/
// mdx_ref.py + gen-fixture.py), and the STFT half of that reference is checked
// against torch's own stft/istft by tools/check-torch.py — the step where a
// transcription could otherwise drift with nothing watching.
//
// It also guards the two tables that are copies of upstream data and would rot
// in silence: the per-model n_fft/dim_f/compensate values, and the asset pins.
// A wrong `compensate` is a stem at the wrong level forever; a wrong pin is an
// install that downloads 67 MB and refuses it.
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const APP = __dirname;

let failures = 0;
const check = (n, c, extra) => {
  console.log((c ? 'PASS' : 'FAIL') + ' — ' + n + (extra !== undefined && !c ? '  ' + JSON.stringify(extra) : ''));
  if (!c) failures++;
};
const near = (a, b, tol) => Math.abs(a - b) <= tol;

// ---- load the shipped modules exactly as the GIF would run them -------------
const sandbox = { window: {}, atob, btoa, console, Math, setTimeout };
vm.createContext(sandbox);
for (const f of ['fft.js', 'mdx.js', 'wav.js', 'onnxseg.js', 'models.js']) {
  vm.runInContext(fs.readFileSync(path.join(APP, f), 'utf8'), sandbox, { filename: f });
}
const FFT = sandbox.window.VRFFT, MDX = sandbox.window.VRMDX;
const WAV = sandbox.window.VRWAV, CAT = sandbox.window.VR_MODELS;
const ONNX = sandbox.window.VRONNX;
check('the shipped modules load and attach their globals',
  !!(FFT && FFT.fft && MDX && MDX.demix && WAV && WAV.encodeWav && CAT && CAT.models && ONNX && ONNX.dynamicTime));

// ---- the FFT ----------------------------------------------------------------
// The MDX n_fft values are 5120, 6144 and 7680: none is a power of two, all are
// 2^a * {1,3,5,15}. A radix-2-only transform silently cannot do any of them.
{
  const naive = (re, im, inv) => {
    const n = re.length, R = new Float64Array(n), I = new Float64Array(n), s = inv ? 1 : -1;
    for (let k = 0; k < n; k++) {
      let ar = 0, ai = 0;
      for (let t = 0; t < n; t++) {
        const a = s * 2 * Math.PI * k * t / n, c = Math.cos(a), d = Math.sin(a);
        ar += re[t] * c - im[t] * d; ai += re[t] * d + im[t] * c;
      }
      R[k] = ar; I[k] = ai;
    }
    return [R, I];
  };
  let worst = 0;
  for (const n of [3, 5, 15, 16, 48, 80, 240, 960]) {
    const re = new Float64Array(n), im = new Float64Array(n);
    for (let i = 0; i < n; i++) { re[i] = Math.sin(i * 1.7) + 0.3 * Math.cos(i * 0.11); im[i] = Math.cos(i * 2.3); }
    const [er, ei] = naive(re, im, false);
    const a = Float64Array.from(re), b = Float64Array.from(im);
    FFT.fft(a, b, n, false);
    for (let i = 0; i < n; i++) worst = Math.max(worst, Math.abs(a[i] - er[i]), Math.abs(b[i] - ei[i]));
  }
  check('the FFT agrees with a naive DFT at every radix it has to handle', worst < 1e-9, worst);

  let rt = 0, par = 0;
  for (const n of [1024, 4096, 5120, 6144, 7680]) {
    const re = new Float64Array(n), im = new Float64Array(n);
    for (let i = 0; i < n; i++) re[i] = Math.sin(i * 0.017) + Math.sin(i * 0.9) * 0.3;
    const a = Float64Array.from(re), b = Float64Array.from(im);
    FFT.fft(a, b, n, false);
    let e = 0, s2 = 0;
    for (let i = 0; i < n; i++) { e += a[i] * a[i] + b[i] * b[i]; s2 += re[i] * re[i]; }
    par = Math.max(par, Math.abs(e / n / s2 - 1));
    FFT.fft(a, b, n, true);
    for (let i = 0; i < n; i++) rt = Math.max(rt, Math.abs(a[i] / n - re[i]), Math.abs(b[i] / n));
  }
  check('every model n_fft round-trips and satisfies Parseval', rt < 1e-12 && par < 1e-12, { rt, par });
}

// ---- the two windows are NOT the same array ---------------------------------
// UVR uses torch.hann_window(periodic=True) for the STFT and np.hanning
// (symmetric) for the chunk overlap-add, one line apart in demix(). Collapsing
// them into one helper is the single easiest way to break this port.
{
  const p = MDX.hannPeriodic(8), s = MDX.hannSymmetric(8);
  check('hannPeriodic is torch.hann_window(periodic=True)',
    near(p[0], 0, 1e-15) && near(p[4], 1, 1e-15) && !near(p[7], 0, 1e-9), Array.from(p));
  check('hannSymmetric is np.hanning: zero at BOTH ends',
    near(s[0], 0, 1e-15) && near(s[7], 0, 1e-15) && near(s[1], 0.1882550990706332, 1e-12), Array.from(s));
  check('np.hanning(1) is [1], not [0] — the last chunk can be one sample long',
    MDX.hannSymmetric(1).length === 1 && MDX.hannSymmetric(1)[0] === 1);
}

// ---- reflect padding --------------------------------------------------------
// np.pad(x, 2, 'reflect') on [1..5] is [3,2,1,2,3,4,5,4,3] — the edge sample is
// NOT repeated. 'edge' or 'symmetric' here puts a step into every frame.
{
  const x = Float64Array.from([1, 2, 3, 4, 5]);
  const out = MDX.reflectPad(x, 2, new Float64Array(9));
  check('reflectPad matches numpy/torch reflect padding',
    Array.from(out).join(',') === '3,2,1,2,3,4,5,4,3', Array.from(out));
}

// ---- STFT -> tensor -> STFT round-trip --------------------------------------
// With dim_f taken all the way to the Nyquist bin and the model stood down, the
// pair must reconstruct the chunk. This is the assertion that the plane order
// (ch0.real, ch0.imag, ch1.real, ch1.imag), the freq_pad and the sum-of-w^2
// envelope division are all right at once.
{
  const nFft = 4096, hop = 1024, dimT = 16, dimF = nFft / 2 + 1;
  const T = hop * (dimT - 1);
  const L = new Float64Array(T), R = new Float64Array(T);
  for (let i = 0; i < T; i++) { L[i] = Math.sin(i * 0.03) * 0.4; R[i] = Math.cos(i * 0.011) * 0.3 + Math.sin(i * 0.7) * 0.1; }
  const sc = MDX.scratchFor(nFft, hop, dimF, dimT);
  const t = MDX.chunkToTensor([L, R], nFft, hop, dimF, dimT, sc);
  const oL = new Float64Array(T), oR = new Float64Array(T);
  MDX.tensorToChunk(t, nFft, hop, dimF, dimT, sc, oL, oR);
  // bins 0..2 are zeroed on the way in (`spek[:, :, :3, :] *= 0`), so the DC
  // and the two lowest bins are legitimately missing from the reconstruction.
  let worst = 0;
  for (let i = nFft; i < T - nFft; i++) worst = Math.max(worst, Math.abs(oL[i] - L[i]), Math.abs(oR[i] - R[i]));
  check('STFT -> the model tensor -> iSTFT reconstructs the chunk', worst < 2e-3, worst);
  // ...to the RIGHT channel. A single sample cannot say so — two different
  // signals cross often — so this is the energy of the whole interior.
  let dR = 0, dCross = 0, n = 0;
  for (let i = nFft; i < T - nFft; i++) {
    dR += (oR[i] - R[i]) ** 2; dCross += (oR[i] - L[i]) ** 2; n++;
  }
  check('...and the two channels did not swap',
    Math.sqrt(dR / n) < 2e-3 && Math.sqrt(dCross / n) > 0.05, { toR: Math.sqrt(dR / n), toL: Math.sqrt(dCross / n) });
  let lowBins = 0;
  for (let p = 0; p < 4; p++) for (let b = 0; b < 3; b++) for (let f = 0; f < dimT; f++) {
    if (t[(p * dimF + b) * dimT + f] !== 0) lowBins++;
  }
  check('the three lowest bins are zeroed before the model sees them (spek[:, :, :3, :] *= 0)', lowBins === 0, lowBins);
}

// ---- demix, against the numpy reference -------------------------------------
{
  const doc = JSON.parse(fs.readFileSync(path.join(APP, 'vocal-remover-mdx.json'), 'utf8'));
  // The same 32-bit xorshift gen-fixture.py runs, so the fixture stores only
  // the OUTPUT — a 40000-sample input does not belong in a repo.
  const xorshift = (seed, n) => {
    let x = seed >>> 0; const o = new Float64Array(n);
    for (let i = 0; i < n; i++) {
      x ^= (x << 13) >>> 0; x >>>= 0; x ^= x >>> 17; x ^= (x << 5) >>> 0; x >>>= 0;
      o[i] = (x / 4294967296) * 2 - 1;
    }
    return o;
  };
  const f32 = (b64) => { const b = Buffer.from(b64, 'base64'); return new Float32Array(b.buffer, b.byteOffset, b.length / 4); };

  const run = (async () => {
    for (const c of doc.cases) {
      const raw = xorshift(c.seed, c.T * 2);
      const L = new Float32Array(c.T), R = new Float32Array(c.T);
      for (let i = 0; i < c.T; i++) { L[i] = raw[2 * i]; R[i] = raw[2 * i + 1]; }
      // gen-fixture.py's stand-in model: a frequency-dependent gain, chosen so
      // a transposed plane or a swapped real/imag cannot cancel out.
      const gain = new Float64Array(c.dimF);
      for (let f = 0; f < c.dimF; f++) gain[f] = 0.3 + 0.7 * f / c.dimF;
      const model = async (t) => {
        const o = new Float32Array(t.length);
        for (let p = 0; p < 4; p++) for (let f = 0; f < c.dimF; f++) {
          const b = (p * c.dimF + f) * c.dimT;
          for (let k = 0; k < c.dimT; k++) o[b + k] = Math.fround(t[b + k] * gain[f]);
        }
        return o;
      };
      const cfg = { nFft: c.nFft, hop: c.hop, dimF: c.dimF, dimT: c.dimT, compensate: c.compensate };
      let chunks = 0;
      const out = await MDX.demix([L, R], cfg, c.matchMix ? null : model,
        { matchMix: c.matchMix, onProgress: () => chunks++ });

      check(c.name + ': demix runs the number of chunks UVR would',
        chunks === c.chunks && MDX.chunkCount(c.T, cfg, c.matchMix) === c.chunks,
        { ran: chunks, predicted: MDX.chunkCount(c.T, cfg, c.matchMix), expected: c.chunks });

      const eL = f32(c.sampledL), eR = f32(c.sampledR);
      let worst = 0;
      for (let i = 0; i < eL.length; i++) {
        worst = Math.max(worst, Math.abs(out[0][i * c.stride] - eL[i]), Math.abs(out[1][i * c.stride] - eR[i]));
      }
      check(c.name + ': every sample matches the numpy reference', worst < 1e-5, worst);

      let finite = true, rmsL = 0;
      for (let i = 0; i < c.T; i++) { if (!isFinite(out[0][i]) || !isFinite(out[1][i])) finite = false; rmsL += out[0][i] * out[0][i]; }
      // The overlap window is zero at each chunk's ends, so `divider` genuinely
      // holds zeros — at the two positions the trim then discards. A NaN
      // reaching the output means the trim moved.
      check(c.name + ': nothing NaN survives the trim', finite);
      check(c.name + ': the level matches the reference too', near(Math.sqrt(rmsL / c.T), c.rms[0], 1e-4),
        { got: Math.sqrt(rmsL / c.T), want: c.rms[0] });
    }
  })();

  // ---- the tables that are copies of upstream -------------------------------
  run.then(() => {
    const pins = JSON.parse(fs.readFileSync(path.join(APP, 'MODEL-PINS.json'), 'utf8'));
    const manifest = JSON.parse(fs.readFileSync(path.join(APP, 'manifest.json'), 'utf8'));

    for (const p of pins.pins) {
      const m = CAT.models[p.id];
      check(p.id + ': models.js carries UVR’s own model_data values', !!m
        && m.nFft === p.modelData.mdx_n_fft_scale_set
        && m.dimF === p.modelData.mdx_dim_f_set
        && m.dimT === Math.pow(2, p.modelData.mdx_dim_t_set)
        && m.compensate === p.modelData.compensate
        && m.uvrHash === p.uvrHash,
        m && { nFft: m.nFft, dimF: m.dimF, dimT: m.dimT, compensate: m.compensate });

      const a = (manifest.assets || []).find((x) => x.path === m.asset);
      check(p.id + ': the manifest pins the exact bytes MODEL-PINS.json records',
        !!a && a.sha256 === p.sha256 && a.bytes === p.bytes && a.bytes === m.bytes,
        a);
      check(p.id + ': the pin is a hash, not a hope', !!a && /^[0-9a-f]{64}$/.test(a.sha256));
    }

    // Every model the app can reach must have somewhere to come from, and every
    // asset the OS downloads must be one the app reads: either mismatch costs a
    // user 67 MB or an app that silently only ever self-tests.
    const wanted = Object.keys(CAT.models).filter((k) => !CAT.models[k].selfTest).map((k) => CAT.models[k].asset);
    const pinned = (manifest.assets || []).map((a) => a.path);
    check('every model asset models.js reads is pinned, and nothing else is',
      wanted.slice().sort().join(',') === pinned.slice().sort().join(','), { wanted, pinned });

    // MDX_NET_FREQ_CUT is [Vocals, Instrumental]: the frequency-cut subtraction
    // applies to the main model and NOT to the karaoke one, whose primary stem
    // UVR renames to backing_only.
    check('freqCut follows UVR’s MDX_NET_FREQ_CUT, not a guess',
      CAT.models['inst-hq3'].freqCut === true && CAT.models['kara2'].freqCut === false);
    check('the karaoke model’s own output is the BACKING side (UVR.py BV_VOCAL_STEM)',
      CAT.models['kara2'].primaryStem === 'Backing Vocals' && CAT.models['kara2'].secondaryStem === 'Lead Vocals');

    // Every job's chain has to name models that exist, and the two-model job
    // has to start with one that produces a Vocals stem for the second to split.
    for (const id of Object.keys(CAT.jobs)) {
      const chain = CAT.jobs[id].chain;
      check('job "' + id + '" names only models that exist', chain.every((k) => !!CAT.models[k]), chain);
    }
    const chained = CAT.jobs.split4.chain;
    check('the vocal-split chain starts with a model that yields a Vocals stem',
      chained.length === 2 && [CAT.models[chained[0]].primaryStem, CAT.models[chained[0]].secondaryStem].includes('Vocals'));

    // capabilities.gpu arrived in build 1250; assets in 1178.
    check('minBuild is the floor its capabilities actually need',
      manifest.minBuild >= 1381 && !!manifest.capabilities.gpu && !!manifest.capabilities.wasm, manifest.minBuild);
    check('the manifest declares no network of any kind',
      !manifest.capabilities.network && !manifest.capabilities.api && !manifest.hosts);

    // ---- the ONNX time-dim patcher -------------------------------------------
    // onnxseg.js rewrites each graph input/output's fixed 256-frame time axis
    // to the symbolic "time", so a GPU-constrained device can create the
    // session at a smaller segment (freeDimensionOverrides). The check here is
    // INDEPENDENT: a second, separately-written protobuf reader parses the
    // patched bytes back, so the patcher cannot grade its own homework. The
    // checked-in self-test model has the same [batch, 4, dim_f, 256] shape as
    // the real UVR exports, which is exactly why it is the fixture.
    {
      const readVarint = (b, p) => {
        let v = 0, m = 1, x;
        do { x = b[p++]; v += (x & 127) * m; m *= 128; } while (x & 128);
        return [v, p];
      };
      // Walk one message body, returning [{no, wire, val|sub}] — enough of the
      // wire format to reach a shape, nothing more.
      const fields = (b, s, e) => {
        const out = [];
        let p = s;
        while (p < e) {
          let key, len;
          [key, p] = readVarint(b, p);
          const no = Math.floor(key / 8), wire = key % 8;
          if (wire === 0) { let v; [v, p] = readVarint(b, p); out.push({ no, wire, val: v }); }
          else if (wire === 2) { [len, p] = readVarint(b, p); out.push({ no, wire, s: p, e: p + len }); p += len; }
          else if (wire === 5) p += 4;
          else if (wire === 1) p += 8;
          else throw new Error('wire ' + wire);
        }
        return out;
      };
      const readDims = (b, vi) => {
        const type = fields(b, vi.s, vi.e).find((f) => f.no === 2);
        const tensor = fields(b, type.s, type.e).find((f) => f.no === 1);
        const shape = fields(b, tensor.s, tensor.e).find((f) => f.no === 2);
        return fields(b, shape.s, shape.e).filter((f) => f.no === 1).map((d) => {
          const fs2 = fields(b, d.s, d.e);
          const v = fs2.find((f) => f.no === 1), n = fs2.find((f) => f.no === 2);
          return n ? Buffer.from(b.slice(n.s, n.e)).toString() : v.val;
        });
      };
      const dimsOf = (bytes) => {
        const graph = fields(bytes, 0, bytes.length).find((f) => f.no === 7);
        const io = fields(bytes, graph.s, graph.e).filter((f) => f.no === 11 || f.no === 12);
        return io.map((vi) => readDims(bytes, vi));
      };

      const orig = new Uint8Array(fs.readFileSync(path.join(APP, 'vendor', 'selftest.onnx')));
      const before = Buffer.from(orig).toString('base64');
      const patched = ONNX.dynamicTime(orig);
      check('the patcher leaves the original bytes alone (the pin keeps meaning the pin)',
        Buffer.from(orig).toString('base64') === before);
      check('...and rewrites ONLY the time axis: [batch_size, 4, dim_f, time] in and out',
        JSON.stringify(dimsOf(patched)) === JSON.stringify([['batch_size', 4, 1024, 'time'], ['batch_size', 4, 1024, 'time']]),
        dimsOf(patched));
      check('...growing the file by exactly the two 3-byte dims it replaced',
        patched.length === orig.length + 6, { before: orig.length, after: patched.length });
      check('patching an already-dynamic model changes nothing (idempotent)',
        Buffer.from(ONNX.dynamicTime(patched)).equals(Buffer.from(patched)));
      let threw = false;
      try { ONNX.dynamicTime(new Uint8Array([1, 2, 3, 4, 5])); } catch (e) { threw = true; }
      check('bytes that are not a model it recognises THROW rather than run wrong', threw);
    }

    // ---- the WAV writer -----------------------------------------------------
    {
      const L = Float32Array.from([0, 0.5, -0.5, 1.5]), R = Float32Array.from([0, -0.5, 0.5, -1.5]);
      const p16 = WAV.encodeWav([L, R], 44100, 16);
      const dv = new DataView(p16.bytes.buffer);
      const tag = (o) => String.fromCharCode(p16.bytes[o], p16.bytes[o + 1], p16.bytes[o + 2], p16.bytes[o + 3]);
      check('16-bit output is a RIFF/WAVE PCM file at 44100, stereo',
        tag(0) === 'RIFF' && tag(8) === 'WAVE' && dv.getUint16(20, true) === 1
        && dv.getUint16(22, true) === 2 && dv.getUint32(24, true) === 44100 && dv.getUint16(34, true) === 16);
      check('16-bit output is the right length', p16.bytes.length === 44 + 4 * 2 * 2);
      check('samples past full scale are clipped and COUNTED, not normalised away',
        p16.clipped === 2 && dv.getInt16(44 + 3 * 4, true) === 32767, p16.clipped);
      const f32out = WAV.encodeWav([L, R], 44100, 32);
      const dv2 = new DataView(f32out.bytes.buffer);
      check('32-bit float output declares format 3 and keeps the over-scale sample',
        dv2.getUint16(20, true) === 3 && dv2.getUint16(34, true) === 32
        && near(dv2.getFloat32(44 + 3 * 8, true), 1.5, 1e-6) && f32out.clipped === 0);
    }

    console.log(failures ? ('\n' + failures + ' FAILURE(S)') : '\nALL PASS');
    process.exit(failures ? 1 : 0);
  }).catch((e) => { console.error(e); process.exit(1); });
}
